// List of common skills for the skills selector
export const commonSkills = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Ruby",
  "Go",
  "PHP",
  "Swift",
  "Kotlin",
  "Rust",
  "Scala",
  "R",
  "MATLAB",
  "SQL",
  "HTML",
  "CSS",
  "Perl",
  "Bash/Shell Scripting",
  
  // Web Development
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "ASP.NET Core",
  "Laravel",
  "Spring Boot",
  "GraphQL",
  "REST API",
  "WordPress",
  "Bootstrap",
  "Tailwind CSS",
  "SASS/SCSS",
  "Redux",
  "WebSockets",
  
  // Mobile Development
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "SwiftUI",
  "Jetpack Compose",
  "Ionic",
  "Cordova",
  
  // DevOps & Cloud
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "GitLab CI/CD",
  "GitHub Actions",
  "Terraform",
  "Ansible",
  "Puppet",
  "Chef",
  "Linux Administration",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  
  // Data Science & Analytics
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Analysis",
  "Data Visualization",
  "Statistical Analysis",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Jupyter Notebooks",
  "Tableau",
  "Power BI",
  "Big Data",
  "Apache Spark",
  "Hadoop",
  
  // Databases
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "SQLite",
  "Oracle Database",
  "Microsoft SQL Server",
  "Cassandra",
  "DynamoDB",
  "Firebase",
  "Elasticsearch",
  "Neo4j",
  
  // Soft Skills
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Critical Thinking",
  "Leadership",
  "Time Management",
  "Project Management",
  "Adaptability",
  "Creativity",
  "Emotional Intelligence",
  "Conflict Resolution",
  "Public Speaking",
  "Technical Writing",
  
  // Project Management & Tools
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "JIRA",
  "Trello",
  "Asana",
  "Confluence",
  "Git",
  "GitHub",
  "BitBucket",
  "Azure DevOps",
  
  // Design & UX
  "UI Design",
  "UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Information Architecture",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Accessibility",
]; 